### ISSUE TITLE
how to use the dataset？

### ISSUE THREAD

**Issue by Lzvvvvv** [Partaourides/SERN#1]
Hello，
I'm sorry to bother you again. I've got the complete IEMOCAP dataset, but I don't know what data should be placed in these two directories,since there is no paths as the following.
“dialogs_files = glob.glob("IEOMAP_dataset/Sentences/*.txt")
    dialogs_emotions_files = glob.glob("IEOMAP_dataset/Classification/*.txt")”
Looking forward to your reply !

**Comment by Partaourides** [comment]
Using the glob module you can get all the .txt files that are available in the specified folder e.g. IEOMAP_dataset/Sentences/. 
The \*.txt allows to get all the available prefixes of .txt files (e.g. example1.txt, example2.txt)
dialogs_files = glob.glob("IEOMAP_dataset/Sentences/\*.txt")
dialogs_emotions_files = glob.glob("IEOMAP_dataset/Classification/\*.txt")

We pre-process all the available examples of the dataset (sentences and their classifications)
for i, j in zip(dialogs_files, dialogs_emotions_files):

**Comment by Lzvvvvv** [comment]
I have put the .txt in the dataset to the specified path, but it always reports errors. I think it is the problem of the dataset, but I don't know how to solve it.


it reports like this：.Can you tell me what I did wrong?
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harris"<notifications@github.com&gt;; 
发送时间: 2020年6月27日(星期六) 晚上9:30
收件人: "Partaourides/SERN"<SERN@noreply.github.com&gt;; 
抄送: "Lzv-"<1286292325@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Partaourides/SERN] how to use the dataset？ (#1)





 
Using the glob module you can get all the .txt files that are available in the specified folder e.g. IEOMAP_dataset/Sentences/.
 The *.txt allows to get all the available prefixes of .txt files (e.g. example1.txt, example2.txt)
 dialogs_files = glob.glob("IEOMAP_dataset/Sentences/*.txt")
 dialogs_emotions_files = glob.glob("IEOMAP_dataset/Classification/*.txt")
 
We pre-process all the available examples of the dataset (sentences and their classifications)
 for i, j in zip(dialogs_files, dialogs_emotions_files):

**Comment by Partaourides** [comment]
Can you post the information about the error

**Comment by Lzvvvvv** [comment]
There is the full information




 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harris"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 下午2:16
收件人: "Partaourides/SERN"<SERN@noreply.github.com&gt;; 
抄送: "Lzv-"<1286292325@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Partaourides/SERN] how to use the dataset？ (#1)





 
Can you post the information about the error

**Comment by Partaourides** [comment]
There is no information available

**Comment by Lzvvvvv** [comment]
Sorry,I  just sent it in the form of a picture. It's not shown.


Traceback (most recent call last):
 File "C:/Users/12862/Desktop/第十七周/代码/SERN-master/run_AC.py", line 51, in <module>
    args.num_desired_classes)
  File "C:\Users\12862\Desktop\第十七周\代码\SERN-master\emotion_recognition_with_dialog_dependence.py", line 54, in model_with_dialog_dependence
    num_desired_classes=num_desired_classes)
  File "C:\Users\12862\Desktop\第十七周\代码\SERN-master\IEOMAP_dataset_AC.py", line 71, in dataset
    if 'X' not in utterance_id and dialog_emotions[utterance_id] not in removed_classes:# FIXME for 5-class and 4-class classification
KeyError: 'Ang01'

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harris"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 下午3:43
收件人: "Partaourides/SERN"<SERN@noreply.github.com&gt;; 
抄送: "Lzv-"<1286292325@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Partaourides/SERN] how to use the dataset？ (#1)





 
There is no information available

**Comment by Partaourides** [comment]
You will need to debug the code.
Check the variables at "dialog_emotions[utterance_id] not in removed_classes", namely dialog_emotions, utternace_id, removed_classes, to see what they contain.
This can be done with proper debugging or just a print before the if statement.
From there it will give you a clue about the error.

**Comment by Lzvvvvv** [comment]
> You will need to debug the code.
> Check the variables at "dialog_emotions[utterance_id] not in removed_classes", namely dialog_emotions, utternace_id, removed_classes, to see what they contain.
> This can be done with proper debugging or just a print before the if statement.
> From there it will give you a clue about the error.

Thank you. I'll  try.
